# for encryption we need cryptography module which needs to be installed from outside using pip install cryptography
from cryptography.fernet import Fernet #this module allows you to encrypt text 

'''
# generating a key from module ->we will use this only once
def write_key():
    key = Fernet.generate_key()
    with open("key.key","wb") as key_file:
        key_file.write(key)
write_key()
'''

# reading the key which was generated by wrie_key()
def load_key():
    with open("key.key","rb") as file:
        key = file.read()
    return key


# master_pwd = input("What is the master password? \n") # note complicated stuff so dont bother now
key = load_key()
fer = Fernet(key) # initilizing the furnet module

# summary of encryption
#   key  + text to encrypt = random text
#   random text + key = text to encrypt

def view():
    with open("C:\\Users\\Sunil\\Desktop\\drive\\python\\python projects\\password manager\\usernames_and_passwords.txt","r") as f:
        for line in f.readlines():
            text = line.rstrip()# rstrip removes the \n from the file as we read
            user,passw = text.split("|")#gives right side of | to passw and leftside of | to user
            print(f"username is: {user} | password is:{fer.decrypt(passw.encode()).decode()}")
            
        
def add():
    username = input("Account Name: ")
    pwd = input("Password: ")

    storage = f"{username}|{fer.encrypt(pwd.encode()).decode()}\n" #we need to encrypt the password

    with open("usernames_and_passwords.txt","a") as f:
        f.write(storage)

while True:
    mode = input("Would you like to add a new password or view existing one (add,view) . Press q to Quit\n")

    if mode=='q':
        exit()

    if mode=="view":
        view()
    elif mode=="add":
        add()
    else:
        print("invalid mode")
        continue


# note -> b"hello" and "hello" are bothe diff first one is byte string and latter is normal one
# SOURCE OF CODE https://youtu.be/DLn3jOsNRVE